server:
  port: 8881

#  http://localhost:8881/actuator/refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server
  rabbitmq:
    host: tencent
    port: 5672
    username: admin
    password: admin
#      uri: localhost:8888/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

