server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/1020983630/SpringcloudConfig
          search-paths: respo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



